### ISSUE TITLE
[UserStory] Create JUnit Test for Redistrctor.java IllegalArgumentException

### ISSUE THREAD

**Issue by Kelzihar** [RD-utopia/redistricting#4]
# User Story
### Essential components
- [x] Title describes the story
- [x] Stakeholder type is identified
- [x] Outcome is described
- [x] Rationale is explicit
- [x] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
**As a**  _Developer_  
**I want**  _a JUnit test that ensures an exception is thrown when null region is used in Redistrictor._  
**so that**  _code is tested to verify values._

## Acceptance Criteria
_(Rules or scenarios are acceptable formats.)_

Write a test that anticipates an IllegalArgumentException when theRegion is null.

_**Scenario 1**_  
**Given**  _A unit test Redistrictor verifying exception throw._  
**when**  _the theRegion has a value of null_  
**then**  _receive IllegalArgumentException_  

## Supporting Information
_(Relevant information, context, resources)_
Refer to issue #69 from the main repo for the reference made there

### Depends On
_(Issues on which this story depends)_
### Dependents
**Issue #28 from the main repo**

**Comment by ghost** [comment]
I believe this issue is closed. Lines 41-44 in RedistrictorTest.java
